#!/usr/bin/env python3
"""Manual review tool for auto-annotated samples."""

from __future__ import annotations

import argparse
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

sys.path.append(str(Path(__file__).parent))

from utils.annotation_io import load_json_any, save_json_utf8


CONFIG_PATH = Path(__file__).parent / "config.yaml"
with open(CONFIG_PATH, encoding="utf-8") as f:
    CONFIG = yaml.safe_load(f)

ACTION_LABELS = {
    "pushup": "Push-up",
    "squat": "Squat",
    "situp": "Sit-up",
    "jump_rope": "Jump Rope",
    "long_jump": "Long Jump",
    "pullup": "Pull-up",
}


def error_codes(action_type: str, errors: list[str]) -> list[str]:
    mapping = {
        item.get("name"): item.get("code")
        for item in CONFIG.get("actions", {})
        .get(action_type, {})
        .get("common_errors", [])
        if isinstance(item, dict)
    }
    return [str(mapping.get(error, error)) for error in errors]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Manual review for annotation JSON files"
    )
    parser.add_argument(
        "--action", type=str, default=None, help="Review one action only"
    )
    parser.add_argument(
        "--queue_file",
        type=str,
        default="",
        help="Review queue JSONL/JSON file generated by prepare_review_queue.py",
    )
    parser.add_argument(
        "--only_unreviewed",
        action="store_true",
        help="Load only samples that are not reviewed yet",
    )
    parser.add_argument(
        "--limit", type=int, default=0, help="Limit number of loaded samples"
    )
    return parser.parse_args()


def load_queue_file(path: Path) -> list[dict[str, Any]]:
    try:
        payload, _ = load_json_any(path)
    except Exception:
        payload = None
    if isinstance(payload, list):
        return [item for item in payload if isinstance(item, dict)]

    records: list[dict[str, Any]] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            import json

            item = json.loads(line)
        except Exception:
            continue
        if isinstance(item, dict):
            records.append(item)
    return records


def load_annotations(
    action_type: str | None = None,
    queue_file: str = "",
    only_unreviewed: bool = False,
    limit: int = 0,
) -> list[dict[str, Any]]:
    samples: list[dict[str, Any]] = []

    if queue_file:
        queue_path = Path(queue_file)
        if not queue_path.is_absolute():
            queue_path = Path(__file__).parent / queue_path
        queue_records = load_queue_file(queue_path)

        for record in queue_records:
            if (
                action_type
                and record.get("action_type") != action_type
                and record.get("action") != action_type
            ):
                continue

            annotation_path = Path(record["annotation_path"])
            if not annotation_path.is_absolute():
                annotation_path = Path(__file__).parent / annotation_path
            if not annotation_path.exists():
                continue

            data, encoding = load_json_any(annotation_path)
            if only_unreviewed and data.get("reviewed"):
                continue

            skeleton_path = record.get("skeleton_path")
            skeleton_value = None
            if skeleton_path:
                skeleton_value = Path(skeleton_path)
                if not skeleton_value.is_absolute():
                    skeleton_value = Path(__file__).parent / skeleton_value

            samples.append(
                {
                    "annotation_path": annotation_path,
                    "skeleton_path": skeleton_value,
                    "data": data,
                    "source_encoding": encoding,
                    "queue_info": record,
                }
            )
    else:
        anno_dir = Path(CONFIG["paths"]["annotations"])
        action_types = [action_type] if action_type else list(CONFIG["actions"].keys())

        for current_action in action_types:
            action_anno_dir = anno_dir / current_action
            if not action_anno_dir.exists():
                continue

            for json_path in sorted(action_anno_dir.glob("*.json")):
                data, encoding = load_json_any(json_path)
                if only_unreviewed and data.get("reviewed"):
                    continue

                skeleton_path = (
                    Path(CONFIG["paths"]["skeletons"])
                    / current_action
                    / f"{data['video_id']}.json"
                )
                if not skeleton_path.exists():
                    skeleton_path = None

                samples.append(
                    {
                        "annotation_path": json_path,
                        "skeleton_path": skeleton_path,
                        "data": data,
                        "source_encoding": encoding,
                        "queue_info": None,
                    }
                )

    if limit > 0:
        samples = samples[:limit]
    return samples


class CLIReviewTool:
    def __init__(self, samples: list[dict[str, Any]]):
        self.samples = samples
        self.current_idx = 0

    def reviewed_count(self) -> int:
        return sum(1 for sample in self.samples if sample["data"].get("reviewed"))

    def display_sample(self, idx: int) -> bool:
        if idx < 0 or idx >= len(self.samples):
            print("Reached the end of the current review list.")
            return False

        sample = self.samples[idx]
        anno = sample["data"]
        quality = anno.get("quality", {})
        queue_info = sample.get("queue_info") or {}
        phase_count = len(set(anno.get("phases", [])))
        expected_phase_count = len(anno.get("phase_names", []))

        print("\n" + "=" * 72)
        print(
            f"Sample {idx + 1}/{len(self.samples)} | reviewed in list: {self.reviewed_count()}"
        )
        print("=" * 72)
        print(f"video_id      : {anno.get('video_id', '-')}")
        action_type = str(anno.get("action_type", "-"))
        print(
            f"action        : {action_type} ({ACTION_LABELS.get(action_type, action_type)})"
        )
        print(f"annotation    : {sample['annotation_path']}")
        print(f"skeleton      : {sample.get('skeleton_path') or '-'}")
        print(f"encoding      : {sample.get('source_encoding', '-')}")
        print(f"auto_annotated: {anno.get('auto_annotated', False)}")
        print(f"reviewed      : {anno.get('reviewed', False)}")
        print(f"phase_count   : {phase_count}/{expected_phase_count or '-'}")
        print(f"score         : {quality.get('overall_score', 'N/A')}")
        print(f"is_standard   : {quality.get('is_standard', False)}")

        errors = quality.get("errors", [])
        display_errors = error_codes(action_type, errors)
        print(
            f"errors        : {', '.join(display_errors) if display_errors else 'none'}"
        )

        if queue_info:
            print(f"queue_rank    : {queue_info.get('rank', '-')}")
            print(f"queue_bucket  : {queue_info.get('bucket', '-')}")
            print(f"review_reason : {queue_info.get('review_reason', '-')}")
            print(f"risk_score    : {queue_info.get('risk_score', '-')}")

        print(
            "Commands: [n] mark reviewed + next | [s] mark reviewed | [k] skip | [p] prev | [u] unreview | [q] quit"
        )
        return True

    def save_annotation(self, idx: int, reviewed: bool) -> None:
        sample = self.samples[idx]
        anno = sample["data"]
        anno["reviewed"] = reviewed
        anno["reviewed_at"] = (
            datetime.now().isoformat(timespec="seconds") if reviewed else None
        )
        save_json_utf8(sample["annotation_path"], anno)
        sample["source_encoding"] = "utf-8"
        print(f"Saved: {sample['annotation_path']}")

    def run(self) -> None:
        print(f"Loaded {len(self.samples)} sample(s) for review")
        while self.current_idx < len(self.samples):
            if not self.display_sample(self.current_idx):
                break

            cmd = input("\nSelect command: ").strip().lower()
            if cmd == "q":
                print("Exit review tool")
                break
            if cmd == "n":
                self.save_annotation(self.current_idx, True)
                self.current_idx += 1
                continue
            if cmd == "s":
                self.save_annotation(self.current_idx, True)
                continue
            if cmd == "u":
                self.save_annotation(self.current_idx, False)
                continue
            if cmd == "k":
                self.current_idx += 1
                continue
            if cmd == "p":
                if self.current_idx > 0:
                    self.current_idx -= 1
                continue
            print("Unknown command")

        print("Review session ended")


def main() -> None:
    args = parse_args()
    samples = load_annotations(
        action_type=args.action,
        queue_file=args.queue_file,
        only_unreviewed=args.only_unreviewed,
        limit=args.limit,
    )
    if not samples:
        print("No samples found. Run Step3 first or check your queue file.")
        return

    CLIReviewTool(samples).run()


if __name__ == "__main__":
    main()
